title: Dewan Mukto's Website
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Dewan Mukto
author-image:   Dreamstudio-lowpoly-pfp.png
author-job:     Writer, Developer, Marketer
author-email:   dewanmukto@gmail.com # Add your email for contant form.
author-twitter: dewan_mukto # Add your twitter account
about-author:   "ğŸ“š  Wordsmith & Technologist \
ğŸ’»  Crafting Stories & Code \
ğŸš€  Digital Marketing Maestro \
ğŸŒ  Exploring the Digital World "

# Social settings
social-twitter:   dewan_mukto
social-facebook: dewanmukto
social-github:    diztil
social-pinterest: 
social-instagram: dewanmukto
social-youtube:
social-vk:   
social-linkedin: dewanmukto

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier:  # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
kramdown: # è§<https://kramdown.gettalong.org/options.html>
  input: GFM # è§<http://jekyllcn.com/docs/configuration/#kramdown>
  syntax_highlighter_opts: # å¯è§<https://kramdown.gettalong.org/syntax_highlighter/rouge.html>
    block:
      disable: true # å…³æ‰ä»£ç å—é»˜è®¤çš„é«˜äº®ï¼Œæ¢ç”¨prismjs
      line_numbers: false #æ¸²æŸ“å‡ºæ¥çš„æ•ˆæœå¥½é¬¼ç•œ
    span:
      disable: true
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
